name: fb
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.8.8
  - fenics==2019.1.0
  - matplotlib
  - meshio=4.3.8
  - numba
  - numpy
  - pandas
  - pip
  - scikit-image
  - scipy>=1.2.1
  - jupyter
  - pip:
    - gmsh==4.7.1
    - tikzplotlib==0.9.12
    - mpld3