name: fem_bem
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.8.8
  - fenics==2019.1.0
  - matplotlib
  - meshio=4.3.8
  - numpy
  - pandas
  - pip
  - scikit-image
  - spyder>=5.0.3
  - spyder-kernels=2.0.3
  - scipy>=1.2.1
  - pip:
    - gmsh==4.7.1
    - numba==0.49.1
    - pip-autoremove==0.9.1
    - tikzplotlib==0.9.12
